# Obtener producto por su id
PUT http://localhost:3000/products/64108d85416fd424c00a313e HTTP/1.1
content-type: application/json

{
    "image": "http://localhost:3000/public/uploads/Gallet-Gourmet-MAH-502-1604698719837.png",
    "brand": "Gallet ",
    "price": 1200,
    "countInStock":100,
    "rating": null,
    "numReviews": null,
    "isFeatured": true,
    "name": "Actualizado",
    "description": "Hotdog Maker - 380W, for 1-12 hotdogs, 2x switches, 2 vertical push-pins, non-stick surface cooking container, removable attachment for cooking 1-6 eggs, can cook corn",
    "category": "5f15d5b2cb4a6642bddc0fe7",
    "reviews": [
      {
        "avatar": "https://pbs.twimg.com/profile_images/1760228143/Vetor-Johnny-Bravo-Vetorizado-Corel_400x400.jpg",
        "name": "Johnny Bravo",
        "review": "Amazing experience all around"
      },
      {
        "avatar": "https://vignette.wikia.nocookie.net/asterix/images/3/3c/Asterix.png",
        "name": "Asterix",
        "review": "It's very hard. Only managed with resource to magic potion"
      },
      {
        "avatar": "https://vignette.wikia.nocookie.net/looneytunes/images/7/7f/Coyote.gif",
        "name": "Wild Coyote",
        "review": "All my trickery and tools paid of. Thank ACME for suggesting this product to me"
      }
    ]
}